version: "2"
run:
  timeout: 10m
linters:
  enable:
    - errorlint
    - loggercheck
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - (github.com/go-kit/kit/log.Logger).Log
    errorlint:
      # Do not check whether fmt.Errorf uses the %w verb for formatting errors.
      errorf: false
      # Do not check for plain type assertions and type switches.
      asserts: false
      # Check for plain error comparisons.
      comparison: true
formatters:
  enable:
    - gofmt
