builds:
  - id: "mimir-whisper-converter"
    main: ./cmd/mimir-whisper-converter
    binary: mimir-whisper-converter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: "datadog-proxy-writes"
    main: ./cmd/datadog-proxy-writes
    binary: datadog-proxy-writes
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: "graphite-proxy-writes"
    main: ./cmd/graphite-proxy-writes
    binary: graphite-proxy-writes
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - none*
    name_template: "mimir-proxies_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
