builds:
  - id: "mimir-whisper-converter"
    main: ./cmd/mimir-whisper-converter
    binary: mimir-whisper-converter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - none*
    name_template: "mimir-whisper-converter_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
