name: conventional-pr

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR title
        uses: grafana/shared-workflows/actions/lint-pr-title@70c40e5b6522c854a55334124545261cae3d4c73 # lint-pr-title/v1.2.4
