on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  DEFAULT_GO_VERSION: 1.20.5

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}
      release_title: >
        ${{ format('mimir-proxies: v{0}.{1}.{2}', steps.release.outputs.major, steps.release.outputs.minor, steps.release.outputs.patch) }}
  call-workflow-build-artifacts:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    uses: ./.github/workflows/build-artifacts.yml
    with:
      release_tag_name:  ${{ needs.release-please.outputs.release_tag_name }}
      release_title:  ${{ needs.release-please.outputs.release_title }}
    secrets: inherit
