on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: read

env:
  DEFAULT_GO_VERSION: 1.24.1

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      release_tag_sha: ${{ steps.release.outputs.release_tag_sha }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}

  # The docs say that release-please is supposed to tag releases automatically,
  # but for some reason that never happens, so we do it manually.
  tag-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Fetch all history for all tags and branches.
        # Needed for the releaser to know what version to tag.
        with:
          fetch-depth: 0
      - name: Tag the created release
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git tag ${{ needs.release-please.outputs.release_tag_name }} ${{ needs.release-please.outputs.release_tag_sha }} -m ${{ needs.release-please.outputs.release_tag_name }}
          git push origin ${{ needs.release-please.outputs.release_tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-build-artifacts:
    needs: [release-please, tag-release]
    if: ${{ needs.release-please.outputs.releases_created }}
    uses: ./.github/workflows/build-artifacts.yml
    with:
      release_tag_name: ${{ needs.release-please.outputs.release_tag_name }}
    secrets: inherit
